/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPWM_H
#define _MOCKPWM_H

#include "unity.h"
#include "Types.h"
#include "pwm.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockpwm_Init(void);
void Mockpwm_Destroy(void);
void Mockpwm_Verify(void);




#define PwmInit_Expect() PwmInit_CMockExpect(__LINE__)
void PwmInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define PwmStart_Expect() PwmStart_CMockExpect(__LINE__)
void PwmStart_CMockExpect(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
