/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockpwm.h"

static const char* CMockString_PwmInit = "PwmInit";
static const char* CMockString_PwmStart = "PwmStart";
static const char* CMockString_pwm = "pwm";

typedef struct _CMOCK_PwmInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_pwm;

} CMOCK_PwmInit_CALL_INSTANCE;

typedef struct _CMOCK_PwmStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_PwmStart_CALL_INSTANCE;

static struct MockpwmInstance
{
  CMOCK_MEM_INDEX_TYPE PwmInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE PwmStart_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockpwm_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.PwmInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PwmInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.PwmStart_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PwmStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockpwm_Init(void)
{
  Mockpwm_Destroy();
}

void Mockpwm_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void PwmInit(int pwm)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PwmInit);
  cmock_call_instance = (CMOCK_PwmInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PwmInit_CallInstance);
  Mock.PwmInit_CallInstance = CMock_Guts_MemNext(Mock.PwmInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_PwmInit,CMockString_pwm);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_pwm, pwm, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_PwmInit(CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance, int pwm);
void CMockExpectParameters_PwmInit(CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance, int pwm)
{
  cmock_call_instance->Expected_pwm = pwm;
}

void PwmInit_CMockExpect(UNITY_LINE_TYPE cmock_line, int pwm)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmInit_CALL_INSTANCE));
  CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmInit_CallInstance = CMock_Guts_MemChain(Mock.PwmInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_PwmInit(cmock_call_instance, pwm);
}

void PwmStart(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PwmStart);
  cmock_call_instance = (CMOCK_PwmStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PwmStart_CallInstance);
  Mock.PwmStart_CallInstance = CMock_Guts_MemNext(Mock.PwmStart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void PwmStart_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmStart_CALL_INSTANCE));
  CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmStart_CallInstance = CMock_Guts_MemChain(Mock.PwmStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

