/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "pwm.h"

static const char* CMockString_PwmInit = "PwmInit";
static const char* CMockString_PwmSetDuty = "PwmSetDuty";
static const char* CMockString_PwmStart = "PwmStart";
static const char* CMockString_cc_reg_val = "cc_reg_val";
static const char* CMockString_channel = "channel";
static const char* CMockString_config = "config";

typedef struct _CMOCK_PwmInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  const Pwm_Cfg_T* Expected_config;
  char IgnoreArg_config;

} CMOCK_PwmInit_CALL_INSTANCE;

typedef struct _CMOCK_PwmStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  const Pwm_Cfg_T* Expected_config;
  char IgnoreArg_config;

} CMOCK_PwmStart_CALL_INSTANCE;

typedef struct _CMOCK_PwmSetDuty_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  const Pwm_Cfg_T* Expected_config;
  Pwm_Timer_Chan_T Expected_channel;
  uint32_t Expected_cc_reg_val;
  char IgnoreArg_config;
  char IgnoreArg_channel;
  char IgnoreArg_cc_reg_val;

} CMOCK_PwmSetDuty_CALL_INSTANCE;

static struct pwmInstance
{
  CMOCK_MEM_INDEX_TYPE PwmInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE PwmStart_CallInstance;
  CMOCK_MEM_INDEX_TYPE PwmSetDuty_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void pwm_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.PwmInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PwmInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.PwmStart_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PwmStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.PwmSetDuty_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_PwmSetDuty);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void pwm_Init(void)
{
  pwm_Destroy();
}

void pwm_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void PwmInit(const Pwm_Cfg_T* config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PwmInit);
  cmock_call_instance = (CMOCK_PwmInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PwmInit_CallInstance);
  Mock.PwmInit_CallInstance = CMock_Guts_MemNext(Mock.PwmInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_config)
  {
    UNITY_SET_DETAILS(CMockString_PwmInit,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_config), (void*)(config), sizeof(const Pwm_Cfg_T), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_PwmInit(CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance, const Pwm_Cfg_T* config);
void CMockExpectParameters_PwmInit(CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance, const Pwm_Cfg_T* config)
{
  cmock_call_instance->Expected_config = config;
  cmock_call_instance->IgnoreArg_config = 0;
}

void PwmInit_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmInit_CALL_INSTANCE));
  CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmInit_CallInstance = CMock_Guts_MemChain(Mock.PwmInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PwmInit_CMockExpect(UNITY_LINE_TYPE cmock_line, const Pwm_Cfg_T* config)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmInit_CALL_INSTANCE));
  CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmInit_CallInstance = CMock_Guts_MemChain(Mock.PwmInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PwmInit(cmock_call_instance, config);
}

void PwmInit_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PwmInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PwmInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_config = 1;
}

void PwmStart(const Pwm_Cfg_T* config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PwmStart);
  cmock_call_instance = (CMOCK_PwmStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PwmStart_CallInstance);
  Mock.PwmStart_CallInstance = CMock_Guts_MemNext(Mock.PwmStart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_config)
  {
    UNITY_SET_DETAILS(CMockString_PwmStart,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_config), (void*)(config), sizeof(const Pwm_Cfg_T), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_PwmStart(CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance, const Pwm_Cfg_T* config);
void CMockExpectParameters_PwmStart(CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance, const Pwm_Cfg_T* config)
{
  cmock_call_instance->Expected_config = config;
  cmock_call_instance->IgnoreArg_config = 0;
}

void PwmStart_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmStart_CALL_INSTANCE));
  CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmStart_CallInstance = CMock_Guts_MemChain(Mock.PwmStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PwmStart_CMockExpect(UNITY_LINE_TYPE cmock_line, const Pwm_Cfg_T* config)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmStart_CALL_INSTANCE));
  CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmStart_CallInstance = CMock_Guts_MemChain(Mock.PwmStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PwmStart(cmock_call_instance, config);
}

void PwmStart_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PwmStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PwmStart_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_config = 1;
}

void PwmSetDuty(const Pwm_Cfg_T* config, Pwm_Timer_Chan_T channel, uint32_t cc_reg_val)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_PwmSetDuty);
  cmock_call_instance = (CMOCK_PwmSetDuty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PwmSetDuty_CallInstance);
  Mock.PwmSetDuty_CallInstance = CMock_Guts_MemNext(Mock.PwmSetDuty_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_config)
  {
    UNITY_SET_DETAILS(CMockString_PwmSetDuty,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_config), (void*)(config), sizeof(const Pwm_Cfg_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_channel)
  {
    UNITY_SET_DETAILS(CMockString_PwmSetDuty,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_channel), (void*)(&channel), sizeof(Pwm_Timer_Chan_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cc_reg_val)
  {
    UNITY_SET_DETAILS(CMockString_PwmSetDuty,CMockString_cc_reg_val);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_cc_reg_val, cc_reg_val, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_PwmSetDuty(CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance, const Pwm_Cfg_T* config, Pwm_Timer_Chan_T channel, uint32_t cc_reg_val);
void CMockExpectParameters_PwmSetDuty(CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance, const Pwm_Cfg_T* config, Pwm_Timer_Chan_T channel, uint32_t cc_reg_val)
{
  cmock_call_instance->Expected_config = config;
  cmock_call_instance->IgnoreArg_config = 0;
  memcpy((void*)(&cmock_call_instance->Expected_channel), (void*)(&channel),
         sizeof(Pwm_Timer_Chan_T[sizeof(channel) == sizeof(Pwm_Timer_Chan_T) ? 1 : -1])); /* add Pwm_Timer_Chan_T to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_channel = 0;
  cmock_call_instance->Expected_cc_reg_val = cc_reg_val;
  cmock_call_instance->IgnoreArg_cc_reg_val = 0;
}

void PwmSetDuty_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmSetDuty_CALL_INSTANCE));
  CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmSetDuty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmSetDuty_CallInstance = CMock_Guts_MemChain(Mock.PwmSetDuty_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void PwmSetDuty_CMockExpect(UNITY_LINE_TYPE cmock_line, const Pwm_Cfg_T* config, Pwm_Timer_Chan_T channel, uint32_t cc_reg_val)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PwmSetDuty_CALL_INSTANCE));
  CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmSetDuty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PwmSetDuty_CallInstance = CMock_Guts_MemChain(Mock.PwmSetDuty_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_PwmSetDuty(cmock_call_instance, config, channel, cc_reg_val);
}

void PwmSetDuty_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmSetDuty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PwmSetDuty_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_config = 1;
}

void PwmSetDuty_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmSetDuty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PwmSetDuty_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_channel = 1;
}

void PwmSetDuty_CMockIgnoreArg_cc_reg_val(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PwmSetDuty_CALL_INSTANCE* cmock_call_instance = (CMOCK_PwmSetDuty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PwmSetDuty_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cc_reg_val = 1;
}

