/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _PWM_H
#define _PWM_H

#include "unity.h"
#include "pwm_types.h"
#include "rtos_types_UT.h"
#include "spi_types_mock.h"
#include "pwm.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void pwm_Init(void);
void pwm_Destroy(void);
void pwm_Verify(void);




#define PwmInit_ExpectAnyArgs() PwmInit_CMockExpectAnyArgs(__LINE__)
void PwmInit_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PwmInit_Expect(config) PwmInit_CMockExpect(__LINE__, config)
void PwmInit_CMockExpect(UNITY_LINE_TYPE cmock_line, const Pwm_Cfg_T* config);
#define PwmInit_IgnoreArg_config() PwmInit_CMockIgnoreArg_config(__LINE__)
void PwmInit_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line);
#define PwmStart_ExpectAnyArgs() PwmStart_CMockExpectAnyArgs(__LINE__)
void PwmStart_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PwmStart_Expect(config) PwmStart_CMockExpect(__LINE__, config)
void PwmStart_CMockExpect(UNITY_LINE_TYPE cmock_line, const Pwm_Cfg_T* config);
#define PwmStart_IgnoreArg_config() PwmStart_CMockIgnoreArg_config(__LINE__)
void PwmStart_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line);
#define PwmSetDuty_ExpectAnyArgs() PwmSetDuty_CMockExpectAnyArgs(__LINE__)
void PwmSetDuty_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PwmSetDuty_Expect(config, channel, cc_reg_val) PwmSetDuty_CMockExpect(__LINE__, config, channel, cc_reg_val)
void PwmSetDuty_CMockExpect(UNITY_LINE_TYPE cmock_line, const Pwm_Cfg_T* config, Pwm_Timer_Chan_T channel, uint32_t cc_reg_val);
#define PwmSetDuty_IgnoreArg_config() PwmSetDuty_CMockIgnoreArg_config(__LINE__)
void PwmSetDuty_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line);
#define PwmSetDuty_IgnoreArg_channel() PwmSetDuty_CMockIgnoreArg_channel(__LINE__)
void PwmSetDuty_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line);
#define PwmSetDuty_IgnoreArg_cc_reg_val() PwmSetDuty_CMockIgnoreArg_cc_reg_val(__LINE__)
void PwmSetDuty_CMockIgnoreArg_cc_reg_val(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
