/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "spi.h"

static const char* CMockString_SPI1_IRQHandler = "SPI1_IRQHandler";
static const char* CMockString_SPI2_IRQHandler = "SPI2_IRQHandler";
static const char* CMockString_SPI3_IRQHandler = "SPI3_IRQHandler";
static const char* CMockString_Spi1_RxCompleteCbk = "Spi1_RxCompleteCbk";
static const char* CMockString_Spi2_RxCompleteCbk = "Spi2_RxCompleteCbk";
static const char* CMockString_Spi3_RxCompleteCbk = "Spi3_RxCompleteCbk";
static const char* CMockString_SpiInit = "SpiInit";
static const char* CMockString_SpiReadBuffer = "SpiReadBuffer";
static const char* CMockString_SpiReadIt = "SpiReadIt";
static const char* CMockString_SpiReadSynch = "SpiReadSynch";
static const char* CMockString_config = "config";
static const char* CMockString_dest_ptr = "dest_ptr";
static const char* CMockString_instance = "instance";
static const char* CMockString_mess_len = "mess_len";
static const char* CMockString_storage = "storage";
static const char* CMockString_timeout = "timeout";

typedef struct _CMOCK_SpiInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  Spi_Storage_T* Expected_storage;
  const Spi_Cfg_T* Expected_config;
  char ReturnThruPtr_storage_Used;
  Spi_Storage_T const* ReturnThruPtr_storage_Val;
  size_t ReturnThruPtr_storage_Size;
  char IgnoreArg_storage;
  char IgnoreArg_config;

} CMOCK_SpiInit_CALL_INSTANCE;

typedef struct _CMOCK_SpiReadBuffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t ReturnVal;
  const SPI_TypeDef* Expected_instance;
  char IgnoreArg_instance;

} CMOCK_SpiReadBuffer_CALL_INSTANCE;

typedef struct _CMOCK_SpiReadSynch_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  Std_Return_T ReturnVal;
  Spi_Storage_T* Expected_storage;
  uint8_t* Expected_dest_ptr;
  uint32_t Expected_mess_len;
  uint32_t Expected_timeout;
  char ReturnThruPtr_storage_Used;
  Spi_Storage_T const* ReturnThruPtr_storage_Val;
  size_t ReturnThruPtr_storage_Size;
  char ReturnThruPtr_dest_ptr_Used;
  uint8_t const* ReturnThruPtr_dest_ptr_Val;
  size_t ReturnThruPtr_dest_ptr_Size;
  char IgnoreArg_storage;
  char IgnoreArg_dest_ptr;
  char IgnoreArg_mess_len;
  char IgnoreArg_timeout;

} CMOCK_SpiReadSynch_CALL_INSTANCE;

typedef struct _CMOCK_SpiReadIt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  Spi_Storage_T* Expected_storage;
  uint8_t* Expected_dest_ptr;
  uint32_t Expected_mess_len;
  char ReturnThruPtr_storage_Used;
  Spi_Storage_T const* ReturnThruPtr_storage_Val;
  size_t ReturnThruPtr_storage_Size;
  char ReturnThruPtr_dest_ptr_Used;
  uint8_t const* ReturnThruPtr_dest_ptr_Val;
  size_t ReturnThruPtr_dest_ptr_Size;
  char IgnoreArg_storage;
  char IgnoreArg_dest_ptr;
  char IgnoreArg_mess_len;

} CMOCK_SpiReadIt_CALL_INSTANCE;

typedef struct _CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE;

typedef struct _CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE;

typedef struct _CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE;

typedef struct _CMOCK_SPI1_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_SPI1_IRQHandler_CALL_INSTANCE;

typedef struct _CMOCK_SPI2_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_SPI2_IRQHandler_CALL_INSTANCE;

typedef struct _CMOCK_SPI3_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_SPI3_IRQHandler_CALL_INSTANCE;

static struct spiInstance
{
  CMOCK_MEM_INDEX_TYPE SpiInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE SpiReadBuffer_CallInstance;
  CMOCK_MEM_INDEX_TYPE SpiReadSynch_CallInstance;
  CMOCK_MEM_INDEX_TYPE SpiReadIt_CallInstance;
  CMOCK_MEM_INDEX_TYPE Spi1_RxCompleteCbk_CallInstance;
  CMOCK_MEM_INDEX_TYPE Spi2_RxCompleteCbk_CallInstance;
  CMOCK_MEM_INDEX_TYPE Spi3_RxCompleteCbk_CallInstance;
  CMOCK_MEM_INDEX_TYPE SPI1_IRQHandler_CallInstance;
  CMOCK_MEM_INDEX_TYPE SPI2_IRQHandler_CallInstance;
  CMOCK_MEM_INDEX_TYPE SPI3_IRQHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void spi_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SpiInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SpiInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SpiReadBuffer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SpiReadBuffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SpiReadSynch_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SpiReadSynch);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SpiReadIt_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SpiReadIt);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Spi1_RxCompleteCbk_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Spi1_RxCompleteCbk);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Spi2_RxCompleteCbk_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Spi2_RxCompleteCbk);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Spi3_RxCompleteCbk_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Spi3_RxCompleteCbk);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SPI1_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SPI1_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SPI2_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SPI2_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SPI3_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SPI3_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void spi_Init(void)
{
  spi_Destroy();
}

void spi_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SpiInit(Spi_Storage_T* storage, const Spi_Cfg_T* config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SpiInit);
  cmock_call_instance = (CMOCK_SpiInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SpiInit_CallInstance);
  Mock.SpiInit_CallInstance = CMock_Guts_MemNext(Mock.SpiInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_storage)
  {
    UNITY_SET_DETAILS(CMockString_SpiInit,CMockString_storage);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_storage), (void*)(storage), sizeof(Spi_Storage_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_config)
  {
    UNITY_SET_DETAILS(CMockString_SpiInit,CMockString_config);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_config), (void*)(config), sizeof(const Spi_Cfg_T), cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SpiInit(CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance, Spi_Storage_T* storage, const Spi_Cfg_T* config);
void CMockExpectParameters_SpiInit(CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance, Spi_Storage_T* storage, const Spi_Cfg_T* config)
{
  cmock_call_instance->Expected_storage = storage;
  cmock_call_instance->IgnoreArg_storage = 0;
  cmock_call_instance->ReturnThruPtr_storage_Used = 0;
  cmock_call_instance->Expected_config = config;
  cmock_call_instance->IgnoreArg_config = 0;
}

void SpiInit_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiInit_CALL_INSTANCE));
  CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiInit_CallInstance = CMock_Guts_MemChain(Mock.SpiInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SpiInit_CMockExpect(UNITY_LINE_TYPE cmock_line, Spi_Storage_T* storage, const Spi_Cfg_T* config)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiInit_CALL_INSTANCE));
  CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiInit_CallInstance = CMock_Guts_MemChain(Mock.SpiInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SpiInit(cmock_call_instance, storage, config);
}

void SpiInit_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, Spi_Storage_T const* storage, size_t cmock_size)
{
  CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_storage_Used = 1;
  cmock_call_instance->ReturnThruPtr_storage_Val = storage;
  cmock_call_instance->ReturnThruPtr_storage_Size = cmock_size;
}

void SpiInit_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_storage = 1;
}

void SpiInit_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_config = 1;
}

uint16_t SpiReadBuffer(const SPI_TypeDef* instance)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SpiReadBuffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SpiReadBuffer);
  cmock_call_instance = (CMOCK_SpiReadBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SpiReadBuffer_CallInstance);
  Mock.SpiReadBuffer_CallInstance = CMock_Guts_MemNext(Mock.SpiReadBuffer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_instance)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadBuffer,CMockString_instance);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_instance), (void*)(instance), sizeof(const SPI_TypeDef), cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SpiReadBuffer(CMOCK_SpiReadBuffer_CALL_INSTANCE* cmock_call_instance, const SPI_TypeDef* instance);
void CMockExpectParameters_SpiReadBuffer(CMOCK_SpiReadBuffer_CALL_INSTANCE* cmock_call_instance, const SPI_TypeDef* instance)
{
  cmock_call_instance->Expected_instance = instance;
  cmock_call_instance->IgnoreArg_instance = 0;
}

void SpiReadBuffer_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiReadBuffer_CALL_INSTANCE));
  CMOCK_SpiReadBuffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiReadBuffer_CallInstance = CMock_Guts_MemChain(Mock.SpiReadBuffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SpiReadBuffer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_TypeDef* instance, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiReadBuffer_CALL_INSTANCE));
  CMOCK_SpiReadBuffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiReadBuffer_CallInstance = CMock_Guts_MemChain(Mock.SpiReadBuffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SpiReadBuffer(cmock_call_instance, instance);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SpiReadBuffer_CMockIgnoreArg_instance(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadBuffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadBuffer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_instance = 1;
}

Std_Return_T SpiReadSynch(Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len, uint32_t timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SpiReadSynch);
  cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SpiReadSynch_CallInstance);
  Mock.SpiReadSynch_CallInstance = CMock_Guts_MemNext(Mock.SpiReadSynch_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_storage)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadSynch,CMockString_storage);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_storage), (void*)(storage), sizeof(Spi_Storage_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dest_ptr)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadSynch,CMockString_dest_ptr);
    if (cmock_call_instance->Expected_dest_ptr == NULL)
      { UNITY_TEST_ASSERT_NULL(dest_ptr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_dest_ptr, dest_ptr, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_mess_len)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadSynch,CMockString_mess_len);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_mess_len, mess_len, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadSynch,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout, timeout, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_dest_ptr_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dest_ptr, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dest_ptr, (const void*)cmock_call_instance->ReturnThruPtr_dest_ptr_Val,
      cmock_call_instance->ReturnThruPtr_dest_ptr_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SpiReadSynch(CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len, uint32_t timeout);
void CMockExpectParameters_SpiReadSynch(CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len, uint32_t timeout)
{
  cmock_call_instance->Expected_storage = storage;
  cmock_call_instance->IgnoreArg_storage = 0;
  cmock_call_instance->ReturnThruPtr_storage_Used = 0;
  cmock_call_instance->Expected_dest_ptr = dest_ptr;
  cmock_call_instance->IgnoreArg_dest_ptr = 0;
  cmock_call_instance->ReturnThruPtr_dest_ptr_Used = 0;
  cmock_call_instance->Expected_mess_len = mess_len;
  cmock_call_instance->IgnoreArg_mess_len = 0;
  cmock_call_instance->Expected_timeout = timeout;
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void SpiReadSynch_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, Std_Return_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiReadSynch_CALL_INSTANCE));
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiReadSynch_CallInstance = CMock_Guts_MemChain(Mock.SpiReadSynch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SpiReadSynch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len, uint32_t timeout, Std_Return_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiReadSynch_CALL_INSTANCE));
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiReadSynch_CallInstance = CMock_Guts_MemChain(Mock.SpiReadSynch_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SpiReadSynch(cmock_call_instance, storage, dest_ptr, mess_len, timeout);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(Std_Return_T[sizeof(cmock_to_return) == sizeof(Std_Return_T) ? 1 : -1])); /* add Std_Return_T to :treat_as_array if this causes an error */
}

void SpiReadSynch_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, Spi_Storage_T const* storage, size_t cmock_size)
{
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadSynch_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_storage_Used = 1;
  cmock_call_instance->ReturnThruPtr_storage_Val = storage;
  cmock_call_instance->ReturnThruPtr_storage_Size = cmock_size;
}

void SpiReadSynch_CMockReturnMemThruPtr_dest_ptr(UNITY_LINE_TYPE cmock_line, uint8_t const* dest_ptr, size_t cmock_size)
{
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadSynch_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dest_ptr_Used = 1;
  cmock_call_instance->ReturnThruPtr_dest_ptr_Val = dest_ptr;
  cmock_call_instance->ReturnThruPtr_dest_ptr_Size = cmock_size;
}

void SpiReadSynch_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadSynch_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_storage = 1;
}

void SpiReadSynch_CMockIgnoreArg_dest_ptr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadSynch_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dest_ptr = 1;
}

void SpiReadSynch_CMockIgnoreArg_mess_len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadSynch_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mess_len = 1;
}

void SpiReadSynch_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadSynch_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadSynch_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadSynch_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

void SpiReadIt(Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SpiReadIt);
  cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SpiReadIt_CallInstance);
  Mock.SpiReadIt_CallInstance = CMock_Guts_MemNext(Mock.SpiReadIt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_storage)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadIt,CMockString_storage);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_storage), (void*)(storage), sizeof(Spi_Storage_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_dest_ptr)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadIt,CMockString_dest_ptr);
    if (cmock_call_instance->Expected_dest_ptr == NULL)
      { UNITY_TEST_ASSERT_NULL(dest_ptr, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_dest_ptr, dest_ptr, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_mess_len)
  {
    UNITY_SET_DETAILS(CMockString_SpiReadIt,CMockString_mess_len);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_mess_len, mess_len, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ReturnThruPtr_storage_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(storage, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)storage, (const void*)cmock_call_instance->ReturnThruPtr_storage_Val,
      cmock_call_instance->ReturnThruPtr_storage_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_dest_ptr_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dest_ptr, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dest_ptr, (const void*)cmock_call_instance->ReturnThruPtr_dest_ptr_Val,
      cmock_call_instance->ReturnThruPtr_dest_ptr_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SpiReadIt(CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len);
void CMockExpectParameters_SpiReadIt(CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len)
{
  cmock_call_instance->Expected_storage = storage;
  cmock_call_instance->IgnoreArg_storage = 0;
  cmock_call_instance->ReturnThruPtr_storage_Used = 0;
  cmock_call_instance->Expected_dest_ptr = dest_ptr;
  cmock_call_instance->IgnoreArg_dest_ptr = 0;
  cmock_call_instance->ReturnThruPtr_dest_ptr_Used = 0;
  cmock_call_instance->Expected_mess_len = mess_len;
  cmock_call_instance->IgnoreArg_mess_len = 0;
}

void SpiReadIt_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiReadIt_CALL_INSTANCE));
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiReadIt_CallInstance = CMock_Guts_MemChain(Mock.SpiReadIt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SpiReadIt_CMockExpect(UNITY_LINE_TYPE cmock_line, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SpiReadIt_CALL_INSTANCE));
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SpiReadIt_CallInstance = CMock_Guts_MemChain(Mock.SpiReadIt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SpiReadIt(cmock_call_instance, storage, dest_ptr, mess_len);
}

void SpiReadIt_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, Spi_Storage_T const* storage, size_t cmock_size)
{
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadIt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_storage_Used = 1;
  cmock_call_instance->ReturnThruPtr_storage_Val = storage;
  cmock_call_instance->ReturnThruPtr_storage_Size = cmock_size;
}

void SpiReadIt_CMockReturnMemThruPtr_dest_ptr(UNITY_LINE_TYPE cmock_line, uint8_t const* dest_ptr, size_t cmock_size)
{
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadIt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dest_ptr_Used = 1;
  cmock_call_instance->ReturnThruPtr_dest_ptr_Val = dest_ptr;
  cmock_call_instance->ReturnThruPtr_dest_ptr_Size = cmock_size;
}

void SpiReadIt_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadIt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_storage = 1;
}

void SpiReadIt_CMockIgnoreArg_dest_ptr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadIt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dest_ptr = 1;
}

void SpiReadIt_CMockIgnoreArg_mess_len(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SpiReadIt_CALL_INSTANCE* cmock_call_instance = (CMOCK_SpiReadIt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SpiReadIt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mess_len = 1;
}

void Spi1_RxCompleteCbk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Spi1_RxCompleteCbk);
  cmock_call_instance = (CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Spi1_RxCompleteCbk_CallInstance);
  Mock.Spi1_RxCompleteCbk_CallInstance = CMock_Guts_MemNext(Mock.Spi1_RxCompleteCbk_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void Spi1_RxCompleteCbk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE));
  CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE* cmock_call_instance = (CMOCK_Spi1_RxCompleteCbk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Spi1_RxCompleteCbk_CallInstance = CMock_Guts_MemChain(Mock.Spi1_RxCompleteCbk_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Spi2_RxCompleteCbk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Spi2_RxCompleteCbk);
  cmock_call_instance = (CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Spi2_RxCompleteCbk_CallInstance);
  Mock.Spi2_RxCompleteCbk_CallInstance = CMock_Guts_MemNext(Mock.Spi2_RxCompleteCbk_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void Spi2_RxCompleteCbk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE));
  CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE* cmock_call_instance = (CMOCK_Spi2_RxCompleteCbk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Spi2_RxCompleteCbk_CallInstance = CMock_Guts_MemChain(Mock.Spi2_RxCompleteCbk_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Spi3_RxCompleteCbk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Spi3_RxCompleteCbk);
  cmock_call_instance = (CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Spi3_RxCompleteCbk_CallInstance);
  Mock.Spi3_RxCompleteCbk_CallInstance = CMock_Guts_MemNext(Mock.Spi3_RxCompleteCbk_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void Spi3_RxCompleteCbk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE));
  CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE* cmock_call_instance = (CMOCK_Spi3_RxCompleteCbk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Spi3_RxCompleteCbk_CallInstance = CMock_Guts_MemChain(Mock.Spi3_RxCompleteCbk_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void SPI1_IRQHandler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SPI1_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SPI1_IRQHandler);
  cmock_call_instance = (CMOCK_SPI1_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SPI1_IRQHandler_CallInstance);
  Mock.SPI1_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.SPI1_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SPI1_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SPI1_IRQHandler_CALL_INSTANCE));
  CMOCK_SPI1_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_SPI1_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SPI1_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.SPI1_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void SPI2_IRQHandler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SPI2_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SPI2_IRQHandler);
  cmock_call_instance = (CMOCK_SPI2_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SPI2_IRQHandler_CallInstance);
  Mock.SPI2_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.SPI2_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SPI2_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SPI2_IRQHandler_CALL_INSTANCE));
  CMOCK_SPI2_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_SPI2_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SPI2_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.SPI2_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void SPI3_IRQHandler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SPI3_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SPI3_IRQHandler);
  cmock_call_instance = (CMOCK_SPI3_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SPI3_IRQHandler_CallInstance);
  Mock.SPI3_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.SPI3_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SPI3_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SPI3_IRQHandler_CALL_INSTANCE));
  CMOCK_SPI3_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_SPI3_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SPI3_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.SPI3_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

