/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _SPI_H
#define _SPI_H

#include "unity.h"
#include "pwm_types.h"
#include "rtos_types_UT.h"
#include "spi_types_mock.h"
#include "spi.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void spi_Init(void);
void spi_Destroy(void);
void spi_Verify(void);




#define SpiInit_ExpectAnyArgs() SpiInit_CMockExpectAnyArgs(__LINE__)
void SpiInit_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SpiInit_Expect(storage, config) SpiInit_CMockExpect(__LINE__, storage, config)
void SpiInit_CMockExpect(UNITY_LINE_TYPE cmock_line, Spi_Storage_T* storage, const Spi_Cfg_T* config);
#define SpiInit_ReturnThruPtr_storage(storage) SpiInit_CMockReturnMemThruPtr_storage(__LINE__, storage, sizeof(Spi_Storage_T))
#define SpiInit_ReturnArrayThruPtr_storage(storage, cmock_len) SpiInit_CMockReturnMemThruPtr_storage(__LINE__, storage, cmock_len * sizeof(*storage))
#define SpiInit_ReturnMemThruPtr_storage(storage, cmock_size) SpiInit_CMockReturnMemThruPtr_storage(__LINE__, storage, cmock_size)
void SpiInit_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, Spi_Storage_T const* storage, size_t cmock_size);
#define SpiInit_IgnoreArg_storage() SpiInit_CMockIgnoreArg_storage(__LINE__)
void SpiInit_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line);
#define SpiInit_IgnoreArg_config() SpiInit_CMockIgnoreArg_config(__LINE__)
void SpiInit_CMockIgnoreArg_config(UNITY_LINE_TYPE cmock_line);
#define SpiReadBuffer_ExpectAnyArgsAndReturn(cmock_retval) SpiReadBuffer_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SpiReadBuffer_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define SpiReadBuffer_ExpectAndReturn(instance, cmock_retval) SpiReadBuffer_CMockExpectAndReturn(__LINE__, instance, cmock_retval)
void SpiReadBuffer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_TypeDef* instance, uint16_t cmock_to_return);
#define SpiReadBuffer_IgnoreArg_instance() SpiReadBuffer_CMockIgnoreArg_instance(__LINE__)
void SpiReadBuffer_CMockIgnoreArg_instance(UNITY_LINE_TYPE cmock_line);
#define SpiReadSynch_ExpectAnyArgsAndReturn(cmock_retval) SpiReadSynch_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SpiReadSynch_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, Std_Return_T cmock_to_return);
#define SpiReadSynch_ExpectAndReturn(storage, dest_ptr, mess_len, timeout, cmock_retval) SpiReadSynch_CMockExpectAndReturn(__LINE__, storage, dest_ptr, mess_len, timeout, cmock_retval)
void SpiReadSynch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len, uint32_t timeout, Std_Return_T cmock_to_return);
#define SpiReadSynch_ReturnThruPtr_storage(storage) SpiReadSynch_CMockReturnMemThruPtr_storage(__LINE__, storage, sizeof(Spi_Storage_T))
#define SpiReadSynch_ReturnArrayThruPtr_storage(storage, cmock_len) SpiReadSynch_CMockReturnMemThruPtr_storage(__LINE__, storage, cmock_len * sizeof(*storage))
#define SpiReadSynch_ReturnMemThruPtr_storage(storage, cmock_size) SpiReadSynch_CMockReturnMemThruPtr_storage(__LINE__, storage, cmock_size)
void SpiReadSynch_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, Spi_Storage_T const* storage, size_t cmock_size);
#define SpiReadSynch_ReturnThruPtr_dest_ptr(dest_ptr) SpiReadSynch_CMockReturnMemThruPtr_dest_ptr(__LINE__, dest_ptr, sizeof(uint8_t))
#define SpiReadSynch_ReturnArrayThruPtr_dest_ptr(dest_ptr, cmock_len) SpiReadSynch_CMockReturnMemThruPtr_dest_ptr(__LINE__, dest_ptr, cmock_len * sizeof(*dest_ptr))
#define SpiReadSynch_ReturnMemThruPtr_dest_ptr(dest_ptr, cmock_size) SpiReadSynch_CMockReturnMemThruPtr_dest_ptr(__LINE__, dest_ptr, cmock_size)
void SpiReadSynch_CMockReturnMemThruPtr_dest_ptr(UNITY_LINE_TYPE cmock_line, uint8_t const* dest_ptr, size_t cmock_size);
#define SpiReadSynch_IgnoreArg_storage() SpiReadSynch_CMockIgnoreArg_storage(__LINE__)
void SpiReadSynch_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line);
#define SpiReadSynch_IgnoreArg_dest_ptr() SpiReadSynch_CMockIgnoreArg_dest_ptr(__LINE__)
void SpiReadSynch_CMockIgnoreArg_dest_ptr(UNITY_LINE_TYPE cmock_line);
#define SpiReadSynch_IgnoreArg_mess_len() SpiReadSynch_CMockIgnoreArg_mess_len(__LINE__)
void SpiReadSynch_CMockIgnoreArg_mess_len(UNITY_LINE_TYPE cmock_line);
#define SpiReadSynch_IgnoreArg_timeout() SpiReadSynch_CMockIgnoreArg_timeout(__LINE__)
void SpiReadSynch_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define SpiReadIt_ExpectAnyArgs() SpiReadIt_CMockExpectAnyArgs(__LINE__)
void SpiReadIt_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SpiReadIt_Expect(storage, dest_ptr, mess_len) SpiReadIt_CMockExpect(__LINE__, storage, dest_ptr, mess_len)
void SpiReadIt_CMockExpect(UNITY_LINE_TYPE cmock_line, Spi_Storage_T* storage, uint8_t* dest_ptr, uint32_t mess_len);
#define SpiReadIt_ReturnThruPtr_storage(storage) SpiReadIt_CMockReturnMemThruPtr_storage(__LINE__, storage, sizeof(Spi_Storage_T))
#define SpiReadIt_ReturnArrayThruPtr_storage(storage, cmock_len) SpiReadIt_CMockReturnMemThruPtr_storage(__LINE__, storage, cmock_len * sizeof(*storage))
#define SpiReadIt_ReturnMemThruPtr_storage(storage, cmock_size) SpiReadIt_CMockReturnMemThruPtr_storage(__LINE__, storage, cmock_size)
void SpiReadIt_CMockReturnMemThruPtr_storage(UNITY_LINE_TYPE cmock_line, Spi_Storage_T const* storage, size_t cmock_size);
#define SpiReadIt_ReturnThruPtr_dest_ptr(dest_ptr) SpiReadIt_CMockReturnMemThruPtr_dest_ptr(__LINE__, dest_ptr, sizeof(uint8_t))
#define SpiReadIt_ReturnArrayThruPtr_dest_ptr(dest_ptr, cmock_len) SpiReadIt_CMockReturnMemThruPtr_dest_ptr(__LINE__, dest_ptr, cmock_len * sizeof(*dest_ptr))
#define SpiReadIt_ReturnMemThruPtr_dest_ptr(dest_ptr, cmock_size) SpiReadIt_CMockReturnMemThruPtr_dest_ptr(__LINE__, dest_ptr, cmock_size)
void SpiReadIt_CMockReturnMemThruPtr_dest_ptr(UNITY_LINE_TYPE cmock_line, uint8_t const* dest_ptr, size_t cmock_size);
#define SpiReadIt_IgnoreArg_storage() SpiReadIt_CMockIgnoreArg_storage(__LINE__)
void SpiReadIt_CMockIgnoreArg_storage(UNITY_LINE_TYPE cmock_line);
#define SpiReadIt_IgnoreArg_dest_ptr() SpiReadIt_CMockIgnoreArg_dest_ptr(__LINE__)
void SpiReadIt_CMockIgnoreArg_dest_ptr(UNITY_LINE_TYPE cmock_line);
#define SpiReadIt_IgnoreArg_mess_len() SpiReadIt_CMockIgnoreArg_mess_len(__LINE__)
void SpiReadIt_CMockIgnoreArg_mess_len(UNITY_LINE_TYPE cmock_line);
#define Spi1_RxCompleteCbk_Expect() Spi1_RxCompleteCbk_CMockExpect(__LINE__)
void Spi1_RxCompleteCbk_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Spi2_RxCompleteCbk_Expect() Spi2_RxCompleteCbk_CMockExpect(__LINE__)
void Spi2_RxCompleteCbk_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Spi3_RxCompleteCbk_Expect() Spi3_RxCompleteCbk_CMockExpect(__LINE__)
void Spi3_RxCompleteCbk_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define SPI1_IRQHandler_Expect() SPI1_IRQHandler_CMockExpect(__LINE__)
void SPI1_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define SPI2_IRQHandler_Expect() SPI2_IRQHandler_CMockExpect(__LINE__)
void SPI2_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define SPI3_IRQHandler_Expect() SPI3_IRQHandler_CMockExpect(__LINE__)
void SPI3_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
